### ISSUE TITLE
Generate chords on different testing set

### ISSUE THREAD

**Issue by BeppeMarnell** [juyaolongpaul/harmonic_analysis#18]
Hi guys, I am working on a project for music retrieval and I found your paper. I can run the code but I still have a little bit of trouble to understand if is possible to run the algorithm on a different test set. I could not find any answer about this in your paper and in your website! Thanks a lot!

**Comment by juyaolongpaul** [comment]
Hi @BeppeMarnell, I am glad to hear that you are able to run the code. Regarding running on a different test set, you need to dive into the code and change it for sure, which is out of the scope of my papers, and I admit that the code might take some time and extra help to fully understand it. 

Let me know if you have specific questions, so I can see if I can help you further.

**Comment by BeppeMarnell** [comment]
Thank you so much, keep up with the good stuff then 😊
